<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
      <%@taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
    <%@taglib uri="http://java.sun.com/jsp/jstl/functions" prefix="fn" %> 
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<center>
<form action="upd">
<h3>Update Page</h3>
<br>
<table border="1">
<tr><td>Employee Id: </td><td><input type="text" name=empId readonly="readonly" placeholder="AutoGenerated" value="${d.empId}"></td></tr> 
<tr><td>First Name : </td><td><input type="text" name=firstName  placeholder="First Name " value="${d.firstName}"></td></tr>
<tr><td>Last Name : </td><td><input type="text" name=lastName  placeholder="Last Name "  value="${d.lastName}"></td></tr>
<tr><td>Mobile Number : </td><td><input type="text" name=mobileNumber  placeholder="10-digit-MobileNumber "  value="${d.mobileNumber}"></td></tr>
<tr><td>Email Id : </td><td><input type="text" name=emailId  placeholder="user@gmail.com"  value="${d.emailId}"></td></tr>
<tr><td>Birth Date : </td><td><input type="date" name=dob   value="${d.dob}"></td></tr>

<c:set var="gen" value="${d.gender}"></c:set>
<tr><td> Gender : </td><td><input type="radio" name="gender" value="male" <c:if test="${fn:containsIgnoreCase(gen,'male')}"> checked ="checked"</c:if> > Male
<input type="radio" name="gender" value="female" <c:if test="${fn:containsIgnoreCase(gen,'female')}">checked ="checked"</c:if> > Female</td></tr>

<tr><td> BloodGroup : </td><td>
<select name="bloodGroup">
<Option value="${d.bloodGroup}">${d.bloodGroup}</Option>
<Option value="O+ve">O+ve</Option>
<Option value="O-ve">O-ve</Option>
<Option value="A+ve">A+ve</Option>
<Option value="A-ve">A-ve</Option>
<Option value="B+ve">B+ve</Option>
<Option value="B-ve">B-ve</Option>
<Option value="AB+ve">AB+ve</Option>
<Option value="AB-ve">AB-ve</Option>
</select></td></tr>

<tr><td>Known Languages :</td>
<c:set var="kLang" value="${d.knownLanguages}"></c:set>
<td><input type="checkbox" name="knownLanguages" value="Hindi" <c:if test="${fn:containsIgnoreCase(kLang,'Hindi')}">checked="checked"</c:if>>Hindi
<input type="checkbox" name="knownLanguages" value="Marathi" <c:if test="${fn:containsIgnoreCase(kLang,'Marathi')}">checked="checked"</c:if>>Marathi
<br><input type="checkbox" name="knownLanguages" value="Kannada" <c:if test="${fn:containsIgnoreCase(kLang,'Kannada')}">checked="checked"</c:if>>Kannada
<input type="checkbox" name="knownLanguages" value="English"<c:if test="${fn:containsIgnoreCase(kLang,'English') }">checked="checked"</c:if>>English</td></tr>
<tr><td>User Name : </td><td><input type="text" name="userName" placeholder="user@gmail.com"  value="${d.userName}" /></td></tr>
<td>Password :</td><td><input type="text" name="password" placeholder="Password"  value="${d.password}"/></td></tr>
</table>
<input type="submit" value="Register">
</form>
</center>
</body>
</html>