<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
    pageEncoding="ISO-8859-1"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=ISO-8859-1">
<title>Insert title here</title>
</head>
<body>
<form action="regi">
<center>
<h3>Registration Page</h3>
<br>
<table border="1">
<!-- <tr><td>Employee Id: </td><td><input type="text" name=empId readonly="readonly" placeholder="AutoGenerated"></td></tr> -->
<tr><td>First Name : </td><td><input type="text" name=firstName  placeholder="First Name "></td></tr>
<tr><td>Last Name : </td><td><input type="text" name=lastName  placeholder="Last Name "></td></tr>
<tr><td>Mobile Number : </td><td><input type="text" name=mobileNumber  placeholder="10-digit-MobileNumber "></td></tr>
<tr><td>Email Id : </td><td><input type="text" name=emailId  placeholder="user@gmail.com"></td></tr>
<tr><td>Birth Date : </td><td><input type="date" name=dob  ></td></tr>
<tr><td> Gender : </td><td><input type="radio" name="gender" value="male"> Male
<input type="radio" name="gender" value="female"> Female</td></tr>
<tr><td>BloodGroup :</td><td><select name="bloodGroup">
<Option value="O+ve">O+ve</Option>
<Option value="O-ve">O-ve</Option>
<Option value="A+ve">A+ve</Option>
<Option value="A-ve">A-ve</Option>
<Option value="B+ve">B+ve</Option>
<Option value="B-ve">B-ve</Option>
<Option value="AB+ve">AB+ve</Option>
<Option value="AB-ve">AB-ve</Option>
</select></td></tr>
<tr><td>Known Languages :</td>
<td><input type="checkbox" name="knownLanguages" value="Hindi">Hindi
<input type="checkbox" name="knownLanguages" value="Marathi">Marathi
<br><input type="checkbox" name="knownLanguages" value="Kannada">Kannada
<input type="checkbox" name="knownLanguages" value="English">English</td></tr>
<tr><td>User Name : </td><td><input type="text" name="userName" placeholder="user@gmail.com"/></td></tr>
<tr><td>Password :</td><td><input type="text" name="password" placeholder="Password"/></td></tr>

</table>
<input type="submit" value="Register">

</center>
</form>
</body>
</html>